site_name: datalink
site_description: Aviation datalink decoding for ACARS, VDL Mode 2, HFDL, and Airframes.io feeds
repo_name: xoolive/datalink
repo_url: https://github.com/xoolive/datalink/
site_url: https://mode-s.org/datalink/
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Installation: install.md
  - Sources: sources.md
  - Output format: output.md
  - Configuration: config.md

theme:
  name: material
  logo: images/favicon.png
  favicon: images/favicon.png
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - search.highlight
    - search.suggest
  palette:
    - media: "(prefers-color-scheme)"
      primary: datalink
      accent: datalink
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: datalink
      accent: datalink
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: datalink
      accent: datalink
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.blocks.tab:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      baselevel: 1
