[package]
name = "acars"
description = "Rust library to decode ACARS, VDL2, ADS-C, and CPDLC payloads"
repository = "https://github.com/xoolive/vdl136"
keywords = ["acars", "vdl", "aviation", "decoder"]
authors.workspace = true
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
deku = "0.20.2"
hex = "0.4"
num-complex = "0.4"
base64 = "0.21"
flate2 = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2"
desperado = { version = "0.4.1", features = ["resampler"] }

[dev-dependencies]
