[book]
title = "datalink documentation"
authors = ["Xavier Olive"]
language = "en"
description = "Rust-native aviation datalink decoding framework"
src = "."

[build]
build-dir = "book"

[output.html]
no-section-label = true
git-repository-url = "https://github.com/xoolive/datalink"
additional-css = ["custom.css"]

[output.html.fold]
enable = true
level = 1
